# This is a basic workflow to help you get started with Actions

name: CI

on: push
  
jobs:
  
  build:
    
    runs-on: thomasweise/texlive
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Build
        run: make cv.pdf

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
              cv.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
